FROM node:20-alpine
WORKDIR /app
COPY apps/api/package*.json ./
RUN npm install
COPY prisma ./prisma
RUN npx prisma generate
COPY apps/api ./
RUN npm run build
EXPOSE 4000
CMD ["npm","run","start:prod"]
